language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

deploy:
  provider: packagecloud
  repository: "msstack-artifacts"
  username: "msstack"
  token:
    secure: jloHxptuBYIKqNPDNO+L47Rdb3denL3x1evJ4a+1StVs6QJFz2iUrdshHH3RYuU6MA7lYs1xato9F/o1qOEd4WL67OvR4O5FeJC99iCrWf2v2cRE247a93pTAVGzqaj5HtQNCoI/YSJJBmRA9xIVqisaASmkzRDs0X5l2XLkKwo3338Gh78g9PE+ow8oanLybEHeh1Y8l03k47VF/rPqWZaAy7FKHN8j022u7UsMz2oCzCzNJHEL6kRQthx9mzCygb6Ya6pAnEgNMM830O9ovKlMDcr7eY+96zQEW52ppFRVfwAp1D7t9EegawoXBhNmyy78kf0QcZ4wwQ5az9hlcA1GxS5OwJYfqzMGCfwZYQjZyXyBxFWludnq03Ic/82811qzQ1/3e9z6mnNns0IqYLvNmiIoNIJr4497TBBruoDeuZgeuD0oPNesgBPElBjnndI7qPnDI3LlC9ex0nY8gGi2fIQc0Ec45ZymnEyzqeUTT6Q68PatY49hdGxhxfnrcX62RIE6HGfh7dmKUUy4MQ8/FMB+DWDacJS8u7Qki/gGnJ26liJ0DMM+OS/Z2MhujxrBaafFk+psZEGxF6q0T++p14Z8kdtLgYm2YpEY49L/EEZ3cmHSMW/RfKPN2iGA5HpgZvEmOWefHJ7be1d+xYUBGk41pZYTeub8iXoBd4E=
  on:
      branch: production

env:
  global:
    - secure: QPjuEMA46w59NKmcAv0LHj+0uQTlq2/JXdSSltkujvJJB0O/8jZDuQED7epHl23xGd79KG+fpNosDpGXiGvLBBsR+D8CVug00jez3BxLbOj8W6V4usH7BHwa8z3BMAd/pgUFunUGy47BST5XMlH3TT5SNY7ZwnN1AyzmoF0D7cQlfi+CHKXGfee01wG4TMot17gB5ff5KPDIs+jJJduowDOjWg5Di3vkuzqbY4a9Y+wKqvVQE1fN1Xje6Nxso8ssG4HyU3ZDAWeb7R4EvsTzxsJAKf1WFKMz9XFoq1Ya4M/tamcHyg5j7ZBs3bfdAaundqLFtL5Ne+m5mJrODS49VzHYyKT7hJ3Kp1yEarWuQr2RtqzBeBWJ826FRs3sNRhpr+/iKT8TXqOguaReydNZsuDjKOUwbi42mYrV30cvA59SMeOEWI9baT7T+XJJIbvtyHlWshq61PsF3KrzVAIFrivjXPA0EtynIYCUhdILCb/BL34YlrpmFLHAgGRnkLkry7aGVRNJu09P+MmXjPjtdlZ7eZOOEV5WBbFX5ftoB9v14JjnslK4wEWDLGuOei2iWjczIesPjm0j56Jcz/ZiMFvvKtCkB61JMBIRCftATvz1EN62QO5yPC+awj99uCFCdCheZVmmD/39p7+QKFu8d9jXlFeHJS+EBjP30XI7xPs=
